**Numpy** - [(Num)Numeric + (py)Python]. This libray is used for numeric operation. After reading the data we use numpy to perform activites on numerical data.

In [25]:
# importing the library
import numpy as np 

Array creation (1-D)

In [26]:
lst = [1,2,3,4]
arr = np.array(lst)         #Creating a array
arr

array([1, 2, 3, 4])

2D-Array 

In [27]:
lst1 =[1,2,3,4,5]
lst2 =[6,7,8,9,10]
lst3 = [11,12,13,14,15]

arr1 = np.array([lst1,lst2,lst3])       #multinested list


In [28]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

Indexing of Array : Indexing is similar to list data structure. We can fetch and data based on its index. Array are mutable which means we can re-assign the values of array.

In [29]:
arr[2]

3

In [30]:
arr[3] = 99     #re-assignment

In [31]:
arr

array([ 1,  2,  3, 99])

Slicing : Fetching the entire a row or a part of the row of an array.

In [32]:
arr[1:3]

array([2, 3])

In [33]:
arr[1:]     #fetching the entire row except the 1st element

array([ 2,  3, 99])

In [34]:
# This kind of code is helpful when we are unaware of the size of the datset, we only use (:) colon which print the entire row.
arr[:]      

array([ 1,  2,  3, 99])

In [35]:
arr[:-1]    #fetching the row except the last element

array([1, 2, 3])

In [36]:
# When we need to jump 2 steps and print the data, we use (::) double-colon.
arr[::2]    

array([1, 3])

In [37]:
arr[::-1]       #Reversing the array

array([99,  3,  2,  1])

Working with 2D Array

In [38]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [39]:
arr1[1]     #1st row

array([ 6,  7,  8,  9, 10])

In [40]:
arr1[1:,1:3]

array([[ 7,  8],
       [12, 13]])

In [41]:
arr1[:,::4]

array([[ 1,  5],
       [ 6, 10],
       [11, 15]])

In [42]:
arr1[1:,3:]

array([[ 9, 10],
       [14, 15]])

In [114]:
arr1[:,3:]

array([[ 4,  5],
       [ 9, 10],
       [14, 15]])

## Some inbuilt Function:

*  asarray(): Creates a array.

In [43]:
arr

array([ 1,  2,  3, 99])

In [44]:
np.asarray(arr)     #another way to creating a array

array([ 1,  2,  3, 99])

* n.size: It return the number of element present inside an Array.

In [59]:
arr1.size

15

In [45]:
arr.size

4

*  a.shape: It returns the number of rows and column in a tuple. It basically show the size of the array

In [46]:
arr1.shape      #the array contain 3 rows and 5 column

(3, 5)

In [47]:
arr.shape       #it contain only 4 column

(4,)

*  a.reshape: It reconstruct the array with rows as column and column as row.

In [48]:
arr1.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

*  ndim: It returns the dimension of the array.

In [49]:
arr.ndim

1

In [50]:
arr1.ndim

2

* np.matrix(): It converts the array in a 2-D Matix. 

In [51]:
mat = np.matrix(arr)

In [52]:
mat

matrix([[ 1,  2,  3, 99]])

*  **np.asanyarray(): It converts any datatype to an array.**

In [53]:
np.asanyarray(arr)

array([ 1,  2,  3, 99])

* np.copy(lst): It creates a copy of an array 'lst' and it is stored in a different location, and it is been refered to a variable. If we perform any manipulation on the copied array it won't be reflected on the original array.

In [54]:
a = np.copy(arr)

In [55]:
arr

array([ 1,  2,  3, 99])

In [56]:
a

array([ 1,  2,  3, 99])

In [174]:
a[0] = 99       #Assigning the first index

In [175]:
a   #Changes are visible

array([99,  2,  3, 99])

In [176]:
arr     #NO Change is made

array([ 1,  2,  3, 99])

* np.fromfunction(): It generates a dataset based on the function given.

In [5]:
# This function checks each coordinates whether they are equal or not and return a boolean value.
np.fromfunction(lambda i, j: i == j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [7]:
np.fromfunction(lambda i, j: i*j,(3,3),dtype=int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [22]:
iterable = [i*i for i in range(5)]

In [23]:
np.fromiter(iterable,dtype=int)

array([ 0,  1,  4,  9, 16])

* np.fromstring(): It converts a string data to an Array

In [16]:
# Constructing a 1-D Array with string data based on space as seperator
np.fromstring("45 94 41 100",sep=' ',dtype=int)

array([ 45,  94,  41, 100])