In [48]:
import numpy as np

## Data Generator Function

* np.arange(): This function generates a range between the value of start and stop parameter. It can generate a float point dataset.
* The advantage of .arange() is that it can generates a sequence of number which is not a integer.

In [49]:
np.arange(.2,10.4,.6)

array([ 0.2,  0.8,  1.4,  2. ,  2.6,  3.2,  3.8,  4.4,  5. ,  5.6,  6.2,
        6.8,  7.4,  8. ,  8.6,  9.2,  9.8, 10.4])

In [50]:
list(np.arange(.2,10.4,.6))

[0.2,
 0.8,
 1.4000000000000001,
 2.0000000000000004,
 2.6000000000000005,
 3.2000000000000006,
 3.8000000000000007,
 4.400000000000001,
 5.000000000000001,
 5.6000000000000005,
 6.200000000000001,
 6.800000000000002,
 7.400000000000001,
 8.0,
 8.600000000000001,
 9.200000000000001,
 9.8,
 10.4]

* np.linspace(): It generates a dataset between two points with a step

In [51]:
# Creating an Array with 20 data within a range of 2 to 10.
np.linspace(2,10,20)

array([ 2.        ,  2.42105263,  2.84210526,  3.26315789,  3.68421053,
        4.10526316,  4.52631579,  4.94736842,  5.36842105,  5.78947368,
        6.21052632,  6.63157895,  7.05263158,  7.47368421,  7.89473684,
        8.31578947,  8.73684211,  9.15789474,  9.57894737, 10.        ])

np.logspace(): Returns a logrithmic dataset between two points based on the base (by default it is 10).

In [52]:
np.logspace(1,5,10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [53]:
np.logspace(1,5,base=2)

array([ 2.        ,  2.11642982,  2.2396376 ,  2.37001791,  2.50798829,
        2.65399061,  2.80849244,  2.97198858,  3.14500263,  3.32808868,
        3.52183307,  3.72685628,  3.94381489,  4.17340372,  4.41635805,
        4.67345595,  4.94552078,  5.23342383,  5.53808714,  5.8604864 ,
        6.2016541 ,  6.56268285,  6.94472885,  7.34901563,  7.77683793,
        8.22956587,  8.70864932,  9.21562258,  9.75210923, 10.31982742,
       10.92059526, 11.55633675, 12.22908788, 12.94100316, 13.69436252,
       14.49157863, 15.3352046 , 16.22794219, 17.17265042, 18.17235475,
       19.23025679, 20.3497445 , 21.53440308, 22.78802646, 24.11462942,
       25.51846045, 27.00401538, 28.57605177, 30.23960411, 32.        ])

np.zeros(): Creates a dataset with all zero elements.

In [54]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [55]:
np.zeros((2,4))     #2,4 is the dimension where 2 is rows and 4 is column

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [56]:
# 3-D Dataset
np.zeros((3,4,2))   #3 is the dimension and 4X2 is the shape

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

* np.onces(): Creates a dataset with all one (1) elements.

In [57]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [58]:
# Firstly creating and 2X3 matrix 4 times and again making 3 matix of such type.
np.ones((3,4,2,3))

array([[[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]])

np.eye(): It creates a Identity Matrices, with ones on the diagonal and zeros everywhere.

In [59]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

* np.random.rand(): Create a randam data of a given shape

In [60]:
np.random.rand(2,3)     #(2,3) is the dimension

array([[0.83079812, 0.84845522, 0.81432522],
       [0.85768457, 0.21483949, 0.31490925]])

Difference between rand() and randn():
* In case of rand(), it return a dataset where mean, standard deviation or average can be anything.
* In case of randn(), It return a dataset,on standard Normal Distribution,where mean is 0 and standard deviation is 1.

In [61]:
np.random.randn(2,3)

array([[ 0.31092087,  0.07726391,  0.23604675],
       [-0.12718596, -1.31176476,  0.45550058]])

* randint(): Generates a dataset within a range with the shape of the matrix

In [62]:
arr1 = np.random.randint(1,5,(3,4))
arr1

array([[4, 3, 3, 3],
       [4, 1, 4, 4],
       [2, 4, 1, 2]])

In [63]:
# Reshaping the dataset
ar2 = np.random.randint(1,5,(3,4))

In [64]:
ar2

array([[2, 4, 4, 4],
       [4, 2, 2, 2],
       [4, 2, 4, 4]])

In [65]:
# Creating a dataset with a random values of 1 to 10 with a dimension 5X6.
ar1 = np.random.randint(1,10,(5,6))

In [66]:
ar1

array([[5, 3, 9, 3, 8, 4],
       [6, 8, 4, 5, 8, 4],
       [5, 4, 7, 6, 6, 2],
       [8, 5, 1, 8, 4, 1],
       [3, 1, 5, 6, 6, 6]])

### Applying condition to the Dataset

In [67]:
ar1 > 8    #This will return boolean matrix

array([[False, False,  True, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [68]:
ar1[ar1 > 8]        #It would show all the element greater than 8

array([9])

### Extraction of Data from the Dataset

In [69]:
ar1

array([[5, 3, 9, 3, 8, 4],
       [6, 8, 4, 5, 8, 4],
       [5, 4, 7, 6, 6, 2],
       [8, 5, 1, 8, 4, 1],
       [3, 1, 5, 6, 6, 6]])

In [70]:
ar1[0,0:2]

array([5, 3])

In [71]:
ar1[2:4,2:4]

array([[7, 6],
       [1, 8]])

### Arithmetic Operation

In [72]:
ar3 = np.random.randint(1,4,(3,3))
ar4 = np.random.randint(1,4,(3,3))

In [73]:
ar3

array([[2, 1, 1],
       [1, 1, 3],
       [2, 1, 3]])

In [74]:
ar4

array([[2, 2, 3],
       [3, 1, 2],
       [3, 3, 1]])

In [75]:
ar3+ar4

array([[4, 3, 4],
       [4, 2, 5],
       [5, 4, 4]])

In [76]:
ar4 - ar3

array([[ 0,  1,  2],
       [ 2,  0, -1],
       [ 1,  2, -2]])

In [77]:
ar3 * ar4

array([[4, 2, 3],
       [3, 1, 6],
       [6, 3, 3]])

In [78]:
# Matix Multiplication
ar3 @ ar4 

array([[10,  8,  9],
       [14, 12,  8],
       [16, 14, 11]])

### Numpy Broadcasting

In [79]:
arr2 = np.ones((3,3))

In [80]:
arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [81]:
# Addition of 5 with each element
arr2 + 5

array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]])

In [82]:
a = np.array([1,2,3])

In [84]:
# Addition of an Array and a list
arr2 + a    #Each element of an array is added to a list index by index 

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [100]:
b = np.array([[1,2,3,4]])

In [101]:
arr2 + b    #This would throw an error the shapes of two array are not the same

ValueError: operands could not be broadcast together with shapes (3,3) (1,4) 

To resolve the above error we have to make `arr2` array to the shape of `b` array. Which can be possible by transpose.

In [102]:
arr3 = np.ones((4,3))

In [103]:
arr3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [106]:
ar6 = arr3 + b.T  

In [107]:
ar6

array([[2., 2., 2.],
       [3., 3., 3.],
       [4., 4., 4.],
       [5., 5., 5.]])

In [108]:
# Performing square root
np.sqrt(ar6)

array([[1.41421356, 1.41421356, 1.41421356],
       [1.73205081, 1.73205081, 1.73205081],
       [2.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.23606798]])

In [110]:
np.log2(ar6)

array([[1.        , 1.        , 1.        ],
       [1.5849625 , 1.5849625 , 1.5849625 ],
       [2.        , 2.        , 2.        ],
       [2.32192809, 2.32192809, 2.32192809]])

a.reshape(): Revisited


In [26]:
ar2.reshape(4,3)        #4->Rows and 3-> Column

array([[2, 2, 1],
       [4, 4, 2],
       [2, 4, 1],
       [3, 2, 1]])

In [27]:
# Now here python understand that -1 indicates 3 as because prior to that 4 was given and the probability of 3 is sure.
# Instead of -1 it can be any negative number.
ar2.reshape(4,-1)       

array([[2, 2, 1],
       [4, 4, 2],
       [2, 4, 1],
       [3, 2, 1]])

### Creating the numpy array to a DataFrame

In [111]:
arr = np.eye(5)

In [112]:
import pandas as pd
pd.DataFrame(arr)


0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0