In [1]:
import numpy as np

### Sort, Search & Counting Function

In [38]:
ar = np.array([5,19,8,46,35,68,15])

In [39]:
ar

array([ 5, 19,  8, 46, 35, 68, 15])

In [40]:
np.sort(ar)

array([ 5,  8, 15, 19, 35, 46, 68])

In [52]:
ar1 = np.array([98,46,53,2,198,4,65])

* np.searhsorted(): It return the indices where the element must be inserted so that it maintain the order

In [55]:
np.searchsorted(ar1,10)

6

In [60]:
ar2 = np.array([21,3,0,4,50,1,0,54,0,9])

* np.count_nonzero(): It count the number of non-zero element.

In [61]:
np.count_nonzero(ar2)   

7

* np.where(): It return only those indices which satisfies the condition.

In [63]:
np.where(ar2 > 0)

(array([0, 1, 3, 4, 5, 7, 9], dtype=int64),)

* np.extract(): It return only those element which satisfies a condition.

In [65]:
np.extract(ar2 > 2,ar2)

array([21,  3,  4, 50, 54,  9])

In [66]:
ar1

array([ 98,  46,  53,   2, 198,   4,  65])

In [67]:
a = np.copy(ar1)

* ar1.view(): It creates a swallow copy of the array. If we make changes to the swallow copy it will be reflected on the original array

In [69]:
b = ar1.view()

In [70]:
b

array([ 98,  46,  53,   2, 198,   4,  65])

In [71]:
b[0] = 99

In [72]:
b

array([ 99,  46,  53,   2, 198,   4,  65])

In [74]:
ar1     #As we can see the changes is made in the original copy

array([ 99,  46,  53,   2, 198,   4,  65])